{{ if and .Values.serviceAccount.create (and (or .Values.identity.useDemoCredentials (and .Values.identity.apiKey .Values.identity.agentSecret)) (or .Values.config.useStarterBundle .Values.config.policyBundlePath)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ .Release.Name }}{{ end }}
{{ end }}
